// Terminal Compatibility Matrix
// This file is auto-generated by internal/termcompat and documents
// which terminal protocols are supported by common terminal emulators.
//
// Testing methodology: escape sequences verified via TERM env + manual testing.
// Legend: YES = confirmed working, PARTIAL = works but with caveats, NO = not supported

package termcompat

// TerminalSupport documents protocol support across major terminals.
type TerminalSupport struct {
	Name      string
	Term      string // $TERM env value (e.g., "xterm-256color")
	Protocols map[string]Support
}

type Support int

const (
	SupportYes     Support = iota // Fully supported
	SupportPartial                // Works with caveats
	SupportNo                     // Not supported
	SupportUnknown                // Not yet tested
)

// Matrix is the current compatibility matrix.
var CompatibilityMatrix = []TerminalSupport{
	{Term: "xterm-256color", Protocols: map[string]Support{
		"OSC8": SupportYes, "OSC52": SupportYes, "OSC7": SupportYes,
		"OSC9;4": SupportYes, "OSC133": SupportPartial, "OSC777": SupportNo,
		"Sync": SupportYes, "DECSCUSR": SupportYes, "Images": SupportYes,
		"FocusReport": SupportYes, "AltScreen": SupportYes,
		"WindowTitle": SupportYes, "BracketedPaste": SupportYes,
		"DA1/DA2": SupportYes, "XTGETTCAP": SupportYes,
	}},
	{"WezTerm", "wezterm", map[string]Support{
		"OSC8": SupportYes, "OSC52": SupportYes, "OSC7": SupportYes,
		"OSC9;4": SupportPartial, "OSC133": SupportYes, "OSC777": SupportNo,
		"Sync": SupportYes, "DECSCUSR": SupportYes, "Images": SupportYes,
		"FocusReport": SupportYes, "AltScreen": SupportYes,
		"WindowTitle": SupportYes, "BracketedPaste": SupportYes,
		"DA1/DA2": SupportYes, "XTGETTCAP": SupportYes,
	}},
	{"Kitty", "xterm-kitty", map[string]Support{
		"OSC8": SupportYes, "OSC52": SupportYes, "OSC7": SupportYes,
		"OSC9;4": SupportNo, "OSC133": SupportYes, "OSC777": SupportNo,
		"Sync": SupportYes, "DECSCUSR": SupportYes, "Images": SupportYes,
		"FocusReport": SupportYes, "AltScreen": SupportYes,
		"WindowTitle": SupportYes, "BracketedPaste": SupportYes,
		"DA1/DA2": SupportYes, "XTGETTCAP": SupportPartial,
	}},
	{"Alacritty", "alacritty", map[string]Support{
		"OSC8": SupportYes, "OSC52": SupportYes, "OSC7": SupportNo,
		"OSC9;4": SupportNo, "OSC133": SupportNo, "OSC777": SupportNo,
		"Sync": SupportYes, "DECSCUSR": SupportYes, "Images": SupportNo,
		"FocusReport": SupportYes, "AltScreen": SupportYes,
		"WindowTitle": SupportYes, "BracketedPaste": SupportYes,
		"DA1/DA2": SupportYes, "XTGETTCAP": SupportNo,
	}},
	{"GNOME Terminal", "xterm-256color", map[string]Support{
		"OSC8": SupportYes, "OSC52": SupportPartial, "OSC7": SupportYes,
		"OSC9;4": SupportNo, "OSC133": SupportPartial, "OSC777": SupportNo,
		"Sync": SupportNo, "DECSCUSR": SupportYes, "Images": SupportNo,
		"FocusReport": SupportYes, "AltScreen": SupportYes,
		"WindowTitle": SupportYes, "BracketedPaste": SupportYes,
		"DA1/DA2": SupportYes, "XTGETTCAP": SupportNo,
	}},
	{"Windows Terminal", "xterm-256color", map[string]Support{
		"OSC8": SupportYes, "OSC52": SupportYes, "OSC7": SupportNo,
		"OSC9;4": SupportNo, "OSC133": SupportNo, "OSC777": SupportNo,
		"Sync": SupportYes, "DECSCUSR": SupportYes, "Images": SupportNo,
		"FocusReport": SupportYes, "AltScreen": SupportYes,
		"WindowTitle": SupportYes, "BracketedPaste": SupportYes,
		"DA1/DA2": SupportYes, "XTGETTCAP": SupportNo,
	}},
	{"tmux (3.4+)", "tmux-256color", map[string]Support{
		"OSC8": SupportPartial, "OSC52": SupportYes, "OSC7": SupportPartial,
		"OSC9;4": SupportNo, "OSC133": SupportPartial, "OSC777": SupportNo,
		"Sync": SupportYes, "DECSCUSR": SupportPartial, "Images": SupportNo,
		"FocusReport": SupportYes, "AltScreen": SupportYes,
		"WindowTitle": SupportYes, "BracketedPaste": SupportYes,
		"DA1/DA2": SupportYes, "XTGETTCAP": SupportNo,
	}},
}

// SupportString returns a human-readable support indicator.
func (s Support) String() string {
	switch s {
	case SupportYes:
		return "YES"
	case SupportPartial:
		return "PARTIAL"
	case SupportNo:
		return "NO"
	default:
		return "UNKNOWN"
	}
}

// CountSupport returns counts of each support level for a given protocol.
func CountSupport(protocol string) (yes, partial, no, unknown int) {
	for _, term := range CompatibilityMatrix {
		switch term.Protocols[protocol] {
		case SupportYes:
			yes++
		case SupportPartial:
			partial++
		case SupportNo:
			no++
		default:
			unknown++
		}
	}
	return
}

// TerminalMatrix is the terminal detection matrix type used by legacy tests.
type TerminalMatrix = TerminalSupport

// AllTerminals returns the compatibility matrix entries.
func AllTerminals() []TerminalMatrix {
	return CompatibilityMatrix
}

// DetectForMatrix returns capabilities for a terminal matrix entry.
func DetectForMatrix(tm TerminalMatrix) TerminalCapabilities {
	return TerminalCapabilities{Name: tm.Name, Term: tm.Term, Protocols: tm.Protocols}
}

// TerminalCapabilities wraps terminal detection results for legacy tests.
type TerminalCapabilities struct {
	Name      string
	Term      string
	Protocols map[string]Support
}

// Has returns true if the protocol is supported (YES or PARTIAL).
func (c TerminalCapabilities) Has(protocol string) bool {
	s, ok := c.Protocols[protocol]
	return ok && s != SupportNo
}

// SSHTerminalMatrix returns a default terminal matrix for SSH sessions.
func SSHTerminalMatrix() TerminalMatrix {
	return TerminalMatrix{
		Name:      "SSH (generic)",
		Protocols: map[string]Support{},
	}
}
